using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;

namespace VolleybalCompetition_creator
{
    public class Weekend
    {
        DateTime date;
        public Weekend(string datestr)
        {
            //date = DateTime.Parse(datestr);
            date = DateTime.ParseExact(datestr, "yyyy-MM-dd",null);
        }
    }
    public class Annorama
    {
        public List<Weekend> reeks14 = new List<Weekend>();
        public List<Weekend> reeks12 = new List<Weekend>();
        public List<Weekend> reeks10 = new List<Weekend>();
        public List<Weekend> reeks6 = new List<Weekend>();
        public Annorama()
        {
            Weekend weekend;
            weekend = new Weekend("2013-09-21");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-09-28");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-10-05");
            //reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-10-12");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-10-19");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-10-26");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-11-02");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-11-09");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-11-16");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-11-23");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-11-30");
            //reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-12-07");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-12-14");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-12-21");
            reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2013-12-28");
            //reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-01-04");
            reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-01-11");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-01-18");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-01-25");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-02-01");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-02-08");
            //reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-02-15");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-02-22");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-03-01");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-03-08");
            reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-03-15");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-03-22");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-03-29");
            reeks14.Add(weekend);
            //reeks12.Add(weekend);
            //reeks10.Add(weekend);
            //reeks6.Add(weekend);
            weekend = new Weekend("2014-04-05");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            reeks10.Add(weekend);
            reeks6.Add(weekend);
            weekend = new Weekend("2014-04-12");
            reeks14.Add(weekend);
            reeks12.Add(weekend);
            //reeks10.Add(weekend);
            reeks6.Add(weekend);
            Debug.Assert(reeks14.Count == (14 - 1) * 2);
            Debug.Assert(reeks12.Count == (12 - 1) * 2);
            Debug.Assert(reeks10.Count == (10 - 1) * 2);
            Debug.Assert(reeks6.Count  == (6  - 1) * 2);

        }
    }
}
